[package]
name = "circleci-artifact-proxy"
version = "0.1.0"
authors = ["Jake Howard <git@theorangeone.net>"]

[dependencies]
reqwest = "0.8.5"
rocket = "0.3.8"
rocket_codegen = "0.3.8"
serde = "1.0.34"
serde_derive = "1.0.34"
serde_json = "1.0.13"
url = "1.7.0"
